name: altoke_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  
  # Manejo de estado - BLoC pattern
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.5
  
  # HTTP Client para consumir APIs REST
  dio: ^5.7.0
  
  # Inyección de dependencias
  get_it: ^8.0.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Herramientas para íconos y splash screen
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:

  uses-material-design: true