name: altoke_test
description: "Post-it - Tu idea, tu voz, tu post"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  
  # Manejo de estado - BLoC pattern
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5
  
  # HTTP Client para consumir APIs REST
  dio: ^5.7.0
  
  # Inyección de dependencias
  get_it: ^8.0.0
  
  # URL Launcher para abrir enlaces externos
  url_launcher: ^6.3.1
  
  # SVG support
  flutter_svg: ^2.0.10+1
  
  # Lottie animations
  lottie: ^3.1.2

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Herramientas para íconos y splash screen
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/svg/
    - assets/images/app_icon.svg
    - assets/images/app_icon_rounded.svg
    - assets/animations/

# Configuración para el icono de la app
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#2196F3"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

# Configuración para el splash screen nativo
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_icon.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/app_icon.png
  android_12:
    image: assets/images/app_icon.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/app_icon.png
    icon_background_color_dark: "#FFFFFF"
  web: false